---
- name: install pre-req packages on nodes
  yum:
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "kexec-tools"
      - "sos"
      - "psacct"
      - "ntp"
      - "cockpit"
    state: "present"
  become: true