---
- hosts: bastion
  remote_user: ec2-user
  gather_facts: false
  become: true
  
  tasks:
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://dl.fedoraproject.org/pub/epel/$releasever/$basearch/ 
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    
    - name: install OpenVPN
      yum:
        name:
          - openvpn
        state: latest
    
    - name: enable ipv4 forwarding persistently
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv4.ip_forward = 1'

    - name: enable ipv4 forwarding
      command: sysctl -w net.ipv4.ip_forward=1
    
    - name: copy OVPN config
      copy:
        src: files/server.conf
        dest: /etc/openvpn/server/
    
    - name: copy OVPN shared key
      copy:
        src: files/static.key
        dest: /etc/openvpn/server/

    - name: Start and enable service openvpn-server@server
      service:
        name: openvpn-server@server
        state: started
        enabled: yes

    - debug:
        msg: "Don't forget to change bastion/OpenVPN server IP in client config!"

#- hosts: ocpnodes
#  remote_user: ec2-user
#  gather_facts: false
#  become: true

#  tasks:
#    - name: Add static route for VPN 
#      command: nmcli connection modify "System eth0" +ipv4.routes "192.168.8.0/24 10.0.1.230" && nmcli connection up "System eth0" 

