---
- name: Find ami id with ami
  ec2_ami_find:
     ami_id: "{{ami_id}}"
     region: "{{region}}"
  register: "ami_find"

- name: Provision master
  ec2:
    instance_type: "{{master_ami_size}}"
    image:  "{{ami_find['results'][0]['ami_id']}}"
    region: "{{region}}"
    wait: true
    key_name: "{{aws_key_pair}}"
    vpc_subnet_id: "{{subnet_facts['subnet']['id']}}"
    group: ['{{namespace}}-vpc', '{{namespace}}-public-ingress', '{{namespace}}-public-egress', '{{namespace}}-ssh']
    volumes:
      - device_name: "{{ami_find['results'][0]['root_device_name']}}"
        volume_size: "{{master_root_volume_size}}"
        volume_type: gp2
        delete_on_termination: true
      - device_name: "/dev/xvdb"
        volume_size: "{{docker_volume_size}}"
        volume_type: gp2
        delete_on_termination: true
    count_tag:
      Name: "master-{{namespace}}"
    instance_tags:
      "{'Name':'master-{{namespace}}','namespace':'{{namespace}}','kubernetes.io/cluster/{{namespace}}':'{{namespace}}'}"
    exact_count: 1
  register: ec2_master

- name: allocate a new elastic IP and associate it with master
  ec2_eip:
   device_id: "{{ec2_master['tagged_instances'][0]['id']}}"
   region: "{{region}}"
   in_vpc: "yes"
   release_on_disassociation: true
  register: master_elastic_ip

- name: Provision infra
  ec2:
    instance_type: "{{infra_ami_size}}"
    image:  "{{ami_find['results'][0]['ami_id']}}"
    region: "{{region}}"
    wait: true
    key_name: "{{aws_key_pair}}"
    vpc_subnet_id: "{{subnet_facts['subnet']['id']}}"
    group: ['{{namespace}}-vpc', '{{namespace}}-public-ingress', '{{namespace}}-public-egress', '{{namespace}}-ssh']
    volumes:
      - device_name: "{{ami_find['results'][0]['root_device_name']}}"
        volume_size: "{{infra_root_volume_size}}"
        volume_type: gp2
        delete_on_termination: true
      - device_name: "/dev/xvdb"
        volume_size: "{{docker_volume_size}}"
        volume_type: gp2
        delete_on_termination: true
    count_tag:
      Name: "infra-{{namespace}}"
    instance_tags:
      "{'Name':'infra-{{namespace}}','namespace':'{{namespace}}','kubernetes.io/cluster/{{namespace}}':'{{namespace}}'}"
    exact_count: 1
  register: ec2_infra
  when: standalone_infra_node

- name: allocate a new elastic IP and associate it with infra
  ec2_eip:
   device_id: "{{ec2_infra['tagged_instances'][0]['id']}}"
   region: "{{region}}"
   in_vpc: "yes"
   release_on_disassociation: true
  register: infra_elastic_ip
  when: standalone_infra_node

- name: Provision nodes
  ec2:
    instance_type: "{{node_ami_size}}"
    image:  "{{ami_find['results'][0]['ami_id']}}"
    region: "{{region}}"
    wait: true
    key_name: "{{aws_key_pair}}"
    vpc_subnet_id: "{{subnet_facts['subnet']['id']}}"
    group: ['{{namespace}}-vpc', '{{namespace}}-public-ingress', '{{namespace}}-public-egress', '{{namespace}}-ssh']
    volumes:
      - device_name: "{{ami_find['results'][0]['root_device_name']}}"
        volume_size: "{{node_root_volume_size}}"
        volume_type: gp2
        delete_on_termination: true
      - device_name: "/dev/xvdb"
        volume_size: "{{docker_volume_size}}"
        volume_type: gp2
        delete_on_termination: true
    count_tag:
      Name: "node{{item}}-{{namespace}}"
    instance_tags:
      "{'Name':'node{{item}}-{{namespace}}','namespace':'{{namespace}}','kubernetes.io/cluster/{{namespace}}':'{{namespace}}'}"
    exact_count: 1
    assign_public_ip: yes
  with_sequence: start=1 end={{app_nodes|int}}
  register: ec2_nodes

- debug:
    msg: "{{ec2_nodes}}"

- name: Provision gluster volumes
  ec2_vol:
    instance: "{{item.tagged_instances[0].id}}"
    volume_size: "{{gluster_volume_size}}"
    volume_type: gp2
    device_name: "/dev/xvdc"
    delete_on_termination: true
    region: "{{region}}"
  with_items: "{{ec2_nodes.results[0:3]}}"
  when: install_gluster

- name: Provision bastion
  ec2:
    instance_type: "{{bastion_ami_size}}"
    image:  "{{ami_find['results'][0]['ami_id']}}"
    region: "{{region}}"
    wait: true
    key_name: "{{aws_key_pair}}"
    vpc_subnet_id: "{{subnet_facts['subnet']['id']}}"
    group: ['{{namespace}}-vpc', '{{namespace}}-public-ingress', '{{namespace}}-public-egress', '{{namespace}}-ssh']
    count_tag:
      Name: "bastion-{{namespace}}"
    instance_tags:
      Name: "bastion-{{namespace}}"
      namespace: "{{namespace}}"
    exact_count: 1
    assign_public_ip: yes
    source_dest_check: no
  register: ec2_bastion

- name: Register VM facts
  set_fact:
   master_private_ip: "{{ec2_master['tagged_instances'][0]['private_ip']}}"
   master_public_ip: "{{master_elastic_ip['public_ip']}}"
   master_private_dns_name: "{{ec2_master['tagged_instances'][0]['private_dns_name']}}"
   bastion_private_ip: "{{ec2_bastion['tagged_instances'][0]['private_ip']}}"
   bastion_public_ip: "{{ec2_bastion['tagged_instances'][0]['public_ip']}}"
   bastion_id: "{{ec2_bastion['tagged_instances'][0]['id']}}"

- name: Register Infra VM facts
  set_fact:
   infra_private_ip: "{{ec2_infra['tagged_instances'][0]['private_ip']}}"
   infra_public_ip: "{{infra_elastic_ip['public_ip']}}"
   infra_private_dns_name: "{{ec2_infra['tagged_instances'][0]['private_dns_name']}}"
  when: standalone_infra_node

# Create a dict of node public and private ip addresses
- name: Register Node facts
  set_fact:
    nodes: "{{ nodes|default([]) + [ {'index': item.item, 'public_ip': item.tagged_instances[0].public_ip, 'private_ip': item.tagged_instances[0].private_ip, 'private_dns_name': item.tagged_instances[0].private_dns_name} ] }}"
  with_items: "{{ec2_nodes.results}}"

- name: Node IP provisioned
  debug:
    msg: "{{ nodes }}"

- name: Wait for master and bastion SSH to come up
  local_action: wait_for
                host={{ item }}
                port=22
                state=started
  with_items:
    - "{{bastion_public_ip}}"
    - "{{master_public_ip}}"

- name: Wait for infra SSH to come up
  local_action: wait_for
                host={{ item }}
                port=22
                state=started
  with_items:
    - "{{infra_public_ip}}"
  when: standalone_infra_node

- name: Wait for node SSH to come up
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items: "{{ nodes }}"
