---

- name: Teardown Environment

  hosts: local

  vars_files:
    - vars/aws-config.yml

  pre_tasks:
    - name: Verify Ansible Version
      assert:
        that: 
          - "ansible_version.major == 2"
          - "ansible_version.minor >= 4"
        msg: "This script is only supported with the 2.4 version or later of Ansible"

  post_tasks:
    - name: Completed
      debug:
        msg: 'Finished tearing down environment {{namespace}}'

  roles:
  - define-derived-vars
  - teardown-virtual-machines
  - teardown-security-groups
  - teardown-vpc
  - teardown-dns