---
- name: install pre-req packages on bastion
  yum:
    name:
      - "git"
      - "@Development Tools"
      - "openssl-devel"
      - "python-devel"
      - "gcc"
      - "libffi-devel"
      - "ansible"
      - "atomic-openshift-utils"
    state: "present"
  become: true
  when: deployment_type == 'origin'

- name: install atomic-openshift-utils on bastion
  yum:
    name:
      - "atomic-openshift-utils"
    state: "present"
  become: true
  when: deployment_type != 'origin' and ocp_version is version_compare('3.9', '<=')

- name: install openshift-ansible on bastion
  yum:
    name:
      - "openshift-ansible"
    state: "present"
  become: true
  when: deployment_type != 'origin'

- name: copy ansible.cfg file
  copy:
    src: ../files/ansible.cfg
    dest: "~{{amazon_user}}/ansible.cfg"

- name: copy inventory for openshift istallation
  template:
    src: "../files/openshift_inventory.cfg"
    dest: "~{{amazon_user}}/openshift_inventory.cfg"

- name: checkout openshift ansible repo on bastion
  git:
    repo: "https://github.com/openshift/openshift-ansible"
    dest: "~{{amazon_user}}/openshift-ansible"
    version: "{{openshift_branch}}"
  when: deployment_type == 'origin'

- name: copy script for openshift installation
  template:
    src: "../files/install-openshift.sh"
    dest: "~{{amazon_user}}/install-openshift.sh"
    mode: "0775"
  remote_user: "{{amazon_user}}"

- name: provide details to check installation
  debug:
   msg: "Check file install-openshift.log in Bastion 'ssh ec2-user@{{bastion_public_ip}}' "

- name: run openshift installation script
  shell: './install-openshift.sh {{deployment_type}}  |& tee install-openshift.log'